/**
 * MOLGENIS REST API
 * Documentation for the MOLGENIS Rest API V1 and V2
 *
 * OpenAPI spec version: v1 and v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AttributeResponseV2;
import io.swagger.client.model.EntityTypeResponseV2;
import io.swagger.client.model.Range;
import java.util.ArrayList;
import java.util.List;


/**
 * AttributeResponseV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T17:09:33.994+01:00")
public class AttributeResponseV2   {
  @SerializedName("href")
  private String href = null;

  /**
   * Gets or Sets fieldType
   */
  public enum FieldTypeEnum {
    @SerializedName("BOOL")
    BOOL("BOOL"),
    
    @SerializedName("CATEGORICAL")
    CATEGORICAL("CATEGORICAL"),
    
    @SerializedName("CATEGORICAL_MREF")
    CATEGORICAL_MREF("CATEGORICAL_MREF"),
    
    @SerializedName("COMPOUND")
    COMPOUND("COMPOUND"),
    
    @SerializedName("DATE")
    DATE("DATE"),
    
    @SerializedName("DATE_TIME")
    DATE_TIME("DATE_TIME"),
    
    @SerializedName("DECIMAL")
    DECIMAL("DECIMAL"),
    
    @SerializedName("EMAIL")
    EMAIL("EMAIL"),
    
    @SerializedName("ENUM")
    ENUM("ENUM"),
    
    @SerializedName("FILE")
    FILE("FILE"),
    
    @SerializedName("HTML")
    HTML("HTML"),
    
    @SerializedName("HYPERLINK")
    HYPERLINK("HYPERLINK"),
    
    @SerializedName("INT")
    INT("INT"),
    
    @SerializedName("LONG")
    LONG("LONG"),
    
    @SerializedName("MREF")
    MREF("MREF"),
    
    @SerializedName("ONE_TO_MANY")
    ONE_TO_MANY("ONE_TO_MANY"),
    
    @SerializedName("SCRIPT")
    SCRIPT("SCRIPT"),
    
    @SerializedName("STRING")
    STRING("STRING"),
    
    @SerializedName("TEXT")
    TEXT("TEXT"),
    
    @SerializedName("XREF")
    XREF("XREF");

    private String value;

    FieldTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("fieldType")
  private FieldTypeEnum fieldType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("attributes")
  private List<AttributeResponseV2> attributes = new ArrayList<AttributeResponseV2>();

  @SerializedName("enumOptions")
  private List<String> enumOptions = new ArrayList<String>();

  @SerializedName("maxLength")
  private Long maxLength = null;

  @SerializedName("refEntity")
  private EntityTypeResponseV2 refEntity = null;

  @SerializedName("mappedBy")
  private String mappedBy = null;

  @SerializedName("auto")
  private Boolean auto = null;

  @SerializedName("nillable")
  private Boolean nillable = null;

  @SerializedName("readOnly")
  private Boolean readOnly = null;

  @SerializedName("defaultValue")
  private String defaultValue = null;

  @SerializedName("labelAttribute")
  private Boolean labelAttribute = null;

  @SerializedName("unique")
  private Boolean unique = null;

  @SerializedName("visible")
  private Boolean visible = null;

  @SerializedName("lookupAttribute")
  private Boolean lookupAttribute = null;

  @SerializedName("isAggregatable")
  private Boolean isAggregatable = null;

  @SerializedName("range")
  private Range range = null;

  @SerializedName("expression")
  private String expression = null;

  @SerializedName("visibleExpression")
  private String visibleExpression = null;

  @SerializedName("validationExpression")
  private String validationExpression = null;

  public AttributeResponseV2 href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public AttributeResponseV2 fieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
    return this;
  }

   /**
   * Get fieldType
   * @return fieldType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public FieldTypeEnum getFieldType() {
    return fieldType;
  }

  public void setFieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
  }

  public AttributeResponseV2 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AttributeResponseV2 label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public AttributeResponseV2 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AttributeResponseV2 attributes(List<AttributeResponseV2> attributes) {
    this.attributes = attributes;
    return this;
  }

  public AttributeResponseV2 addAttributesItem(AttributeResponseV2 attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AttributeResponseV2> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeResponseV2> attributes) {
    this.attributes = attributes;
  }

  public AttributeResponseV2 enumOptions(List<String> enumOptions) {
    this.enumOptions = enumOptions;
    return this;
  }

  public AttributeResponseV2 addEnumOptionsItem(String enumOptionsItem) {
    this.enumOptions.add(enumOptionsItem);
    return this;
  }

   /**
   * Get enumOptions
   * @return enumOptions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getEnumOptions() {
    return enumOptions;
  }

  public void setEnumOptions(List<String> enumOptions) {
    this.enumOptions = enumOptions;
  }

  public AttributeResponseV2 maxLength(Long maxLength) {
    this.maxLength = maxLength;
    return this;
  }

   /**
   * Get maxLength
   * @return maxLength
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMaxLength() {
    return maxLength;
  }

  public void setMaxLength(Long maxLength) {
    this.maxLength = maxLength;
  }

  public AttributeResponseV2 refEntity(EntityTypeResponseV2 refEntity) {
    this.refEntity = refEntity;
    return this;
  }

   /**
   * Get refEntity
   * @return refEntity
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntityTypeResponseV2 getRefEntity() {
    return refEntity;
  }

  public void setRefEntity(EntityTypeResponseV2 refEntity) {
    this.refEntity = refEntity;
  }

  public AttributeResponseV2 mappedBy(String mappedBy) {
    this.mappedBy = mappedBy;
    return this;
  }

   /**
   * Get mappedBy
   * @return mappedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMappedBy() {
    return mappedBy;
  }

  public void setMappedBy(String mappedBy) {
    this.mappedBy = mappedBy;
  }

  public AttributeResponseV2 auto(Boolean auto) {
    this.auto = auto;
    return this;
  }

   /**
   * Get auto
   * @return auto
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getAuto() {
    return auto;
  }

  public void setAuto(Boolean auto) {
    this.auto = auto;
  }

  public AttributeResponseV2 nillable(Boolean nillable) {
    this.nillable = nillable;
    return this;
  }

   /**
   * Get nillable
   * @return nillable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getNillable() {
    return nillable;
  }

  public void setNillable(Boolean nillable) {
    this.nillable = nillable;
  }

  public AttributeResponseV2 readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public AttributeResponseV2 defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public AttributeResponseV2 labelAttribute(Boolean labelAttribute) {
    this.labelAttribute = labelAttribute;
    return this;
  }

   /**
   * Get labelAttribute
   * @return labelAttribute
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getLabelAttribute() {
    return labelAttribute;
  }

  public void setLabelAttribute(Boolean labelAttribute) {
    this.labelAttribute = labelAttribute;
  }

  public AttributeResponseV2 unique(Boolean unique) {
    this.unique = unique;
    return this;
  }

   /**
   * Get unique
   * @return unique
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getUnique() {
    return unique;
  }

  public void setUnique(Boolean unique) {
    this.unique = unique;
  }

  public AttributeResponseV2 visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(Boolean visible) {
    this.visible = visible;
  }

  public AttributeResponseV2 lookupAttribute(Boolean lookupAttribute) {
    this.lookupAttribute = lookupAttribute;
    return this;
  }

   /**
   * Get lookupAttribute
   * @return lookupAttribute
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getLookupAttribute() {
    return lookupAttribute;
  }

  public void setLookupAttribute(Boolean lookupAttribute) {
    this.lookupAttribute = lookupAttribute;
  }

  public AttributeResponseV2 isAggregatable(Boolean isAggregatable) {
    this.isAggregatable = isAggregatable;
    return this;
  }

   /**
   * Get isAggregatable
   * @return isAggregatable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getIsAggregatable() {
    return isAggregatable;
  }

  public void setIsAggregatable(Boolean isAggregatable) {
    this.isAggregatable = isAggregatable;
  }

  public AttributeResponseV2 range(Range range) {
    this.range = range;
    return this;
  }

   /**
   * Get range
   * @return range
  **/
  @ApiModelProperty(example = "null", value = "")
  public Range getRange() {
    return range;
  }

  public void setRange(Range range) {
    this.range = range;
  }

  public AttributeResponseV2 expression(String expression) {
    this.expression = expression;
    return this;
  }

   /**
   * Get expression
   * @return expression
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExpression() {
    return expression;
  }

  public void setExpression(String expression) {
    this.expression = expression;
  }

  public AttributeResponseV2 visibleExpression(String visibleExpression) {
    this.visibleExpression = visibleExpression;
    return this;
  }

   /**
   * Get visibleExpression
   * @return visibleExpression
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVisibleExpression() {
    return visibleExpression;
  }

  public void setVisibleExpression(String visibleExpression) {
    this.visibleExpression = visibleExpression;
  }

  public AttributeResponseV2 validationExpression(String validationExpression) {
    this.validationExpression = validationExpression;
    return this;
  }

   /**
   * Get validationExpression
   * @return validationExpression
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValidationExpression() {
    return validationExpression;
  }

  public void setValidationExpression(String validationExpression) {
    this.validationExpression = validationExpression;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeResponseV2 attributeResponseV2 = (AttributeResponseV2) o;
    return Objects.equals(this.href, attributeResponseV2.href) &&
        Objects.equals(this.fieldType, attributeResponseV2.fieldType) &&
        Objects.equals(this.name, attributeResponseV2.name) &&
        Objects.equals(this.label, attributeResponseV2.label) &&
        Objects.equals(this.description, attributeResponseV2.description) &&
        Objects.equals(this.attributes, attributeResponseV2.attributes) &&
        Objects.equals(this.enumOptions, attributeResponseV2.enumOptions) &&
        Objects.equals(this.maxLength, attributeResponseV2.maxLength) &&
        Objects.equals(this.refEntity, attributeResponseV2.refEntity) &&
        Objects.equals(this.mappedBy, attributeResponseV2.mappedBy) &&
        Objects.equals(this.auto, attributeResponseV2.auto) &&
        Objects.equals(this.nillable, attributeResponseV2.nillable) &&
        Objects.equals(this.readOnly, attributeResponseV2.readOnly) &&
        Objects.equals(this.defaultValue, attributeResponseV2.defaultValue) &&
        Objects.equals(this.labelAttribute, attributeResponseV2.labelAttribute) &&
        Objects.equals(this.unique, attributeResponseV2.unique) &&
        Objects.equals(this.visible, attributeResponseV2.visible) &&
        Objects.equals(this.lookupAttribute, attributeResponseV2.lookupAttribute) &&
        Objects.equals(this.isAggregatable, attributeResponseV2.isAggregatable) &&
        Objects.equals(this.range, attributeResponseV2.range) &&
        Objects.equals(this.expression, attributeResponseV2.expression) &&
        Objects.equals(this.visibleExpression, attributeResponseV2.visibleExpression) &&
        Objects.equals(this.validationExpression, attributeResponseV2.validationExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, fieldType, name, label, description, attributes, enumOptions, maxLength, refEntity, mappedBy, auto, nillable, readOnly, defaultValue, labelAttribute, unique, visible, lookupAttribute, isAggregatable, range, expression, visibleExpression, validationExpression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeResponseV2 {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    fieldType: ").append(toIndentedString(fieldType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    enumOptions: ").append(toIndentedString(enumOptions)).append("\n");
    sb.append("    maxLength: ").append(toIndentedString(maxLength)).append("\n");
    sb.append("    refEntity: ").append(toIndentedString(refEntity)).append("\n");
    sb.append("    mappedBy: ").append(toIndentedString(mappedBy)).append("\n");
    sb.append("    auto: ").append(toIndentedString(auto)).append("\n");
    sb.append("    nillable: ").append(toIndentedString(nillable)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    labelAttribute: ").append(toIndentedString(labelAttribute)).append("\n");
    sb.append("    unique: ").append(toIndentedString(unique)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    lookupAttribute: ").append(toIndentedString(lookupAttribute)).append("\n");
    sb.append("    isAggregatable: ").append(toIndentedString(isAggregatable)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    visibleExpression: ").append(toIndentedString(visibleExpression)).append("\n");
    sb.append("    validationExpression: ").append(toIndentedString(validationExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

