/**
 * MOLGENIS REST API
 * Documentation for the MOLGENIS Rest API V1 and V2
 *
 * OpenAPI spec version: v1 and v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * EntityCollectionRequestV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T17:09:33.994+01:00")
public class EntityCollectionRequestV2   {
  @SerializedName("q")
  private String q = null;

  @SerializedName("aggs")
  private String aggs = null;

  @SerializedName("sort")
  private String sort = null;

  @SerializedName("attrs")
  private String attrs = null;

  @SerializedName("start")
  private Integer start = 0;

  @SerializedName("num")
  private Integer num = 0;

  public EntityCollectionRequestV2 q(String q) {
    this.q = q;
    return this;
  }

   /**
   * Get q
   * @return q
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getQ() {
    return q;
  }

  public void setQ(String q) {
    this.q = q;
  }

  public EntityCollectionRequestV2 aggs(String aggs) {
    this.aggs = aggs;
    return this;
  }

   /**
   * Get aggs
   * @return aggs
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAggs() {
    return aggs;
  }

  public void setAggs(String aggs) {
    this.aggs = aggs;
  }

  public EntityCollectionRequestV2 sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public EntityCollectionRequestV2 attrs(String attrs) {
    this.attrs = attrs;
    return this;
  }

   /**
   * Get attrs
   * @return attrs
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAttrs() {
    return attrs;
  }

  public void setAttrs(String attrs) {
    this.attrs = attrs;
  }

  public EntityCollectionRequestV2 start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * Offset in resource collection
   * minimum: 0.0
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "Offset in resource collection")
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }

  public EntityCollectionRequestV2 num(Integer num) {
    this.num = num;
    return this;
  }

   /**
   * Number of resources to retrieve starting at start
   * minimum: 0.0
   * maximum: 10000.0
   * @return num
  **/
  @ApiModelProperty(example = "null", value = "Number of resources to retrieve starting at start")
  public Integer getNum() {
    return num;
  }

  public void setNum(Integer num) {
    this.num = num;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityCollectionRequestV2 entityCollectionRequestV2 = (EntityCollectionRequestV2) o;
    return Objects.equals(this.q, entityCollectionRequestV2.q) &&
        Objects.equals(this.aggs, entityCollectionRequestV2.aggs) &&
        Objects.equals(this.sort, entityCollectionRequestV2.sort) &&
        Objects.equals(this.attrs, entityCollectionRequestV2.attrs) &&
        Objects.equals(this.start, entityCollectionRequestV2.start) &&
        Objects.equals(this.num, entityCollectionRequestV2.num);
  }

  @Override
  public int hashCode() {
    return Objects.hash(q, aggs, sort, attrs, start, num);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityCollectionRequestV2 {\n");
    
    sb.append("    q: ").append(toIndentedString(q)).append("\n");
    sb.append("    aggs: ").append(toIndentedString(aggs)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    num: ").append(toIndentedString(num)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

