/**
 * MOLGENIS REST API
 * Documentation for the MOLGENIS Rest API V1 and V2
 *
 * OpenAPI spec version: v1 and v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EntityTypeResponseV2;
import java.util.ArrayList;
import java.util.List;


/**
 * EntityCollectionResponseV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T17:09:33.994+01:00")
public class EntityCollectionResponseV2   {
  @SerializedName("href")
  private String href = null;

  @SerializedName("meta")
  private EntityTypeResponseV2 meta = null;

  @SerializedName("start")
  private Integer start = null;

  @SerializedName("num")
  private Integer num = null;

  @SerializedName("total")
  private Long total = null;

  @SerializedName("prevHref")
  private String prevHref = null;

  @SerializedName("nextHref")
  private String nextHref = null;

  @SerializedName("items")
  private List<Object> items = new ArrayList<Object>();

  public EntityCollectionResponseV2 href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public EntityCollectionResponseV2 meta(EntityTypeResponseV2 meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EntityTypeResponseV2 getMeta() {
    return meta;
  }

  public void setMeta(EntityTypeResponseV2 meta) {
    this.meta = meta;
  }

  public EntityCollectionResponseV2 start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }

  public EntityCollectionResponseV2 num(Integer num) {
    this.num = num;
    return this;
  }

   /**
   * Get num
   * @return num
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getNum() {
    return num;
  }

  public void setNum(Integer num) {
    this.num = num;
  }

  public EntityCollectionResponseV2 total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public EntityCollectionResponseV2 prevHref(String prevHref) {
    this.prevHref = prevHref;
    return this;
  }

   /**
   * Get prevHref
   * @return prevHref
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPrevHref() {
    return prevHref;
  }

  public void setPrevHref(String prevHref) {
    this.prevHref = prevHref;
  }

  public EntityCollectionResponseV2 nextHref(String nextHref) {
    this.nextHref = nextHref;
    return this;
  }

   /**
   * Get nextHref
   * @return nextHref
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNextHref() {
    return nextHref;
  }

  public void setNextHref(String nextHref) {
    this.nextHref = nextHref;
  }

  public EntityCollectionResponseV2 items(List<Object> items) {
    this.items = items;
    return this;
  }

  public EntityCollectionResponseV2 addItemsItem(Object itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<Object> getItems() {
    return items;
  }

  public void setItems(List<Object> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityCollectionResponseV2 entityCollectionResponseV2 = (EntityCollectionResponseV2) o;
    return Objects.equals(this.href, entityCollectionResponseV2.href) &&
        Objects.equals(this.meta, entityCollectionResponseV2.meta) &&
        Objects.equals(this.start, entityCollectionResponseV2.start) &&
        Objects.equals(this.num, entityCollectionResponseV2.num) &&
        Objects.equals(this.total, entityCollectionResponseV2.total) &&
        Objects.equals(this.prevHref, entityCollectionResponseV2.prevHref) &&
        Objects.equals(this.nextHref, entityCollectionResponseV2.nextHref) &&
        Objects.equals(this.items, entityCollectionResponseV2.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, meta, start, num, total, prevHref, nextHref, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityCollectionResponseV2 {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    num: ").append(toIndentedString(num)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    prevHref: ").append(toIndentedString(prevHref)).append("\n");
    sb.append("    nextHref: ").append(toIndentedString(nextHref)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

