language: java
os: linux
jdk: openjdk11
# Ubuntu 18.04 LTS
dist: bionic
# Caches downloaded libraries between builds
cache:
  directories:
    - '$HOME/.m2/repository'
env:
  # This configures the parallel jobs to run
  jobs:
    - COV_FLAG="api"                       SCRIPT=".ci/jobs/api-tests.sh"
    - COV_FLAG="integration"               SCRIPT=".ci/jobs/integration-tests.sh"
services:
  - postgresql
addons:
  postgresql: "11"
before_install:
  - .ci/services/install-minio-6.sh
  - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'molgenis'"
install:
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -B -V -T4
before_script:
  # Set the max_map_count for elasticsearch, as instructed by maven Elasticsearch plugin docs
  - sudo sysctl -w vm.max_map_count=262144
script:
  - $SCRIPT
notifications:
  slack:
    rooms:
      # Sends build status updates for molgenis/molgenis repo to #pr-platform channel on molgenis-dev slack
      secure: blnxfapt6aAdRDjNvy2Ykp3yPxhRqo0srfz9MI2obKGXFOO2ee+AF0TNosmz9aZG0J3u4e3YI+z9BvjcNMvTzzPCjiLiC3MSbtB9w0SHwhg6q7s1ehVoYKqB22++8S6GEYy5FgBpBLQ+jXEnwiglHfKLowJjvQS8s2NBMhAwEqY=
