/**
 * MOLGENIS REST API
 * Documentation for the MOLGENIS Rest API V1 and V2
 *
 * OpenAPI spec version: v1 and v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.molgenis.graphql.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EntityTypeResponseV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T17:10:22.686+01:00")
public class EntityType
{
  @SerializedName("href")
  private String href = null;

  @SerializedName("hrefCollection")
  private String hrefCollection = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("attributes")
  private List<Attribute> attributes = new ArrayList<Attribute>();

  @SerializedName("labelAttribute")
  private String labelAttribute = null;

  @SerializedName("idAttribute")
  private String idAttribute = null;

  @SerializedName("lookupAttributes")
  private List<String> lookupAttributes = new ArrayList<String>();

  @SerializedName("isAbstract")
  private Boolean isAbstract = null;

  @SerializedName("writable")
  private Boolean writable = null;

  @SerializedName("languageCode")
  private String languageCode = null;

  public EntityType href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public EntityType hrefCollection(String hrefCollection) {
    this.hrefCollection = hrefCollection;
    return this;
  }

   /**
   * Get hrefCollection
   * @return hrefCollection
  **/
  public String getHrefCollection() {
    return hrefCollection;
  }

  public void setHrefCollection(String hrefCollection) {
    this.hrefCollection = hrefCollection;
  }

  public EntityType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EntityType label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public EntityType attributes(List<Attribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public EntityType addAttributesItem(Attribute attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public List<Attribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<Attribute> attributes) {
    this.attributes = attributes;
  }

  public EntityType labelAttribute(String labelAttribute) {
    this.labelAttribute = labelAttribute;
    return this;
  }

   /**
   * Get labelAttribute
   * @return labelAttribute
  **/
  public String getLabelAttribute() {
    return labelAttribute;
  }

  public void setLabelAttribute(String labelAttribute) {
    this.labelAttribute = labelAttribute;
  }

  public EntityType idAttribute(String idAttribute) {
    this.idAttribute = idAttribute;
    return this;
  }

   /**
   * Get idAttribute
   * @return idAttribute
  **/
  public String getIdAttribute() {
    return idAttribute;
  }

  public void setIdAttribute(String idAttribute) {
    this.idAttribute = idAttribute;
  }

  public EntityType lookupAttributes(List<String> lookupAttributes) {
    this.lookupAttributes = lookupAttributes;
    return this;
  }

  public EntityType addLookupAttributesItem(String lookupAttributesItem) {
    this.lookupAttributes.add(lookupAttributesItem);
    return this;
  }

   /**
   * Get lookupAttributes
   * @return lookupAttributes
  **/
  public List<String> getLookupAttributes() {
    return lookupAttributes;
  }

  public void setLookupAttributes(List<String> lookupAttributes) {
    this.lookupAttributes = lookupAttributes;
  }

  public EntityType isAbstract(Boolean isAbstract) {
    this.isAbstract = isAbstract;
    return this;
  }

   /**
   * Get isAbstract
   * @return isAbstract
  **/
  public Boolean getIsAbstract() {
    return isAbstract;
  }

  public void setIsAbstract(Boolean isAbstract) {
    this.isAbstract = isAbstract;
  }

  public EntityType writable(Boolean writable) {
    this.writable = writable;
    return this;
  }

   /**
   * Get writable
   * @return writable
  **/
  public Boolean getWritable() {
    return writable;
  }

  public void setWritable(Boolean writable) {
    this.writable = writable;
  }

  public EntityType languageCode(String languageCode) {
    this.languageCode = languageCode;
    return this;
  }

   /**
   * Get languageCode
   * @return languageCode
  **/
  public String getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityType entityTypeResponseV2 = (EntityType) o;
    return Objects.equals(this.href, entityTypeResponseV2.href) &&
        Objects.equals(this.hrefCollection, entityTypeResponseV2.hrefCollection) &&
        Objects.equals(this.name, entityTypeResponseV2.name) &&
        Objects.equals(this.label, entityTypeResponseV2.label) &&
        Objects.equals(this.attributes, entityTypeResponseV2.attributes) &&
        Objects.equals(this.labelAttribute, entityTypeResponseV2.labelAttribute) &&
        Objects.equals(this.idAttribute, entityTypeResponseV2.idAttribute) &&
        Objects.equals(this.lookupAttributes, entityTypeResponseV2.lookupAttributes) &&
        Objects.equals(this.isAbstract, entityTypeResponseV2.isAbstract) &&
        Objects.equals(this.writable, entityTypeResponseV2.writable) &&
        Objects.equals(this.languageCode, entityTypeResponseV2.languageCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, hrefCollection, name, label, attributes, labelAttribute, idAttribute, lookupAttributes, isAbstract, writable, languageCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTypeResponseV2 {\n");

    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    hrefCollection: ").append(toIndentedString(hrefCollection)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    labelAttribute: ").append(toIndentedString(labelAttribute)).append("\n");
    sb.append("    idAttribute: ").append(toIndentedString(idAttribute)).append("\n");
    sb.append("    lookupAttributes: ").append(toIndentedString(lookupAttributes)).append("\n");
    sb.append("    isAbstract: ").append(toIndentedString(isAbstract)).append("\n");
    sb.append("    writable: ").append(toIndentedString(writable)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

